import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../../components/Navbar/Navbar';

import styles from '../../styles/Connect.module.css';
import { useMoralis } from 'react-moralis';

export default function Connect() {
  const networks = {
    1: {
      code: 'eth',
      name: 'Etherium',
    },
    4: {
      code: 'rinkeby',
      name: 'Rinkeby',
    },
    56: {
      code: 'bsc',
      name: 'Binance Smart Chain',
    },
    97: {
      code: 'bsc testnet',
      name: 'BSC Testnet',
    },
    137: {
      code: 'matic',
      name: 'Polygon',
    },
    80001: {
      code: 'mumbai',
      name: 'Mumbai',
    },
  };

  const { Moralis, isAuthenticated, user } = useMoralis();

  async function connectWallet(provider) {
    switch (provider) {
      case 'metamask':
        await Moralis.authenticate();
        window.localStorage.setItem('provider', 'metamask');
        break;
      case 'trustwallet':
        await Moralis.authenticate();
        window.localStorage.setItem('provider', 'trustwallet');
        break;
      case 'walletconnect':
        await Moralis.authenticate({ provider: provider });
        window.localStorage.setItem('provider', 'walletconnect');
        break;
      default:
        break;
    }
    enabledMoralisWeb3();
    const netid = await Moralis.web3.eth.net.getId();
    if (networks[netid] !== undefined) {
      window.localStorage.setItem('network', networks[netid].name);
    } else {
      alert('Unsupported network');
      window.localStorage.removeItem('network');
      await Moralis.User.logOut();
    }
    window.location.href = '/';
  }

  async function logOut() {
    await Moralis.User.logOut();
    window.localStorage.removeItem('provider');
    window.location.href = '/';
  }

  async function enabledMoralisWeb3() {
    const provider = window.localStorage.getItem('provider');
    switch (provider) {
      case 'walletconnect':
        web3 = await Moralis.enable({ provider: provider });
        break;
      default:
        web3 = await Moralis.enable();
        break;
    }
  }

  function shortenAddress(address) {
    return (
      address.substring(0, 6) +
      '...' +
      address.substring(address.length - 5, address.length)
    );
  }

  if (!isAuthenticated) {
    return (
      <div className={styles.noScroll}>
        <div className={styles.nav}>
          <Navbar></Navbar>
        </div>
        <Head>
          <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
          />
          <script
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
            type="text/javascript"></script>

          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.topInformation}>
          <div>
            <img src="/images/connect/arrow-left-circle.svg" alt="" />
            <p className={styles.backHome}>Back to home</p>
          </div>
          <h2>Connect your wallet</h2>
          <div className={styles.topDescription}>
            Connect wallet with the provided wallets below or{' '}
            <strong> create a new wallet </strong>
          </div>
        </div>
        <img
          className={styles.topBackground}
          src="/images/connect/top-background.svg"
          alt=""
        />
        <img
          className={styles.topBackgroundMobile}
          src="/images/connect/top-background-mobile.svg"
          alt=""
        />

        <main className={styles.main}>
          <div className={styles.mainComponent}>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/metamask.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('metamask')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}> Metamask</h1>
                <div className={styles.walletInformation}>
                  Connect from your mobile phone application
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/coinbase.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('coinbase')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}> Coinbase</h1>
                <div className={styles.walletInformation}>
                  Connect from your mobile phone application
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/bitski.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('bitski')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}> Bitski</h1>
                <div className={styles.walletInformation}>
                  Connect from your mobile phone application
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/wallet-connect.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('walletconnect')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}>Wallet Connect</h1>

                <div className={styles.walletInformation}>
                  Connect from your mobile phone application
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/torus.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('torus')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}> Torus</h1>
                <div className={styles.walletInformation}>
                  Connect with your Google, Facebook or Twitter
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/torus2.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('torus')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}>Torus</h1>

                <div className={styles.walletInformation}>
                  Connect from your mobile phone application
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/fortmetic.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('trustwallet')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}>Fortmatic</h1>

                <div className={styles.walletInformation}>
                  Connect with your Google, Facebook or Twitter
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
            <div className={styles.component}>
              <img
                className={styles.image}
                src="/images/connect/trust_wallet.png"
                alt=""
                width="146"
                height="146"
                onClick={() => connectWallet('trustwallet')}
              />
              <div className={styles.componentInformation}>
                <h1 className={styles.walletTitle}>Wallet Connect</h1>

                <div className={styles.walletInformation}>
                  Connect with your trust wallet
                </div>
              </div>
            </div>
            <img
              className={styles.connectSvg}
              src="/images/connect/connect-wallet.svg"
              alt=""
            />
            <div className={styles.addWallet}>Connect Wallet</div>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div>
      <div>{window.localStorage.getItem('network', '')}</div>
      <div>{shortenAddress(user.get('ethAddress'))}</div>
      <button class="btn btn-warning" onClick={() => logOut()}>
        Disconnect
      </button>
    </div>
  );
}
